SUBROUTINE STICBALAN(BR)
	!计算无摩擦静态接触角
	USE GLOBAL
	USE INTFACE,ONLY:RTSAFE,FUNCD,POW
	IMPLICIT NONE
	TYPE(BEARSYSDATA),INTENT(INOUT),TARGET	:: BR
	REAL(DP) :: CONTANG,LOAD
	INTEGER	 :: I
	REAL(DP) :: A
	
	CONTANG=RTSAFE(FUNCD,0.0_dp,PIO2_D,BR%KPST,BR)
	LOAD=BR%ALOAD/BR%Z/SIN(CONTANG)
	BR%BALNO(:)%INN%ALPHAST=CONTANG
	BR%BALNO(:)%OUT%ALPHAST=CONTANG
	BR%BALNO(:)%INN%P=LOAD
	BR%BALNO(:)%OUT%P=LOAD

	A=BR%ICOM%AND*POW(LOAD,1.0_dp/3.0_DP)

	BR%CONSTT =1.0_DP/(LOAD*BR%MU)
	BR%CONSTP =1.0_DP/LOAD
	BR%CONSTM =1.0_DP/(LOAD*BR%MU*BR%R)
	BR%CONSTMZ=1.0_DP/(LOAD*BR%MU*BR%R*A)

ENDSUBROUTINE STICBALAN

SUBROUTINE PCHAXIS(BR)
	!计算静态接触角
	USE GLOBAL
	USE INTFACE,ONLY:POW
	IMPLICIT NONE
	TYPE(BEARSYSDATA),INTENT(INOUT),TARGET	:: BR
	INTEGER	 :: I
	REAL(DP)	:: P13,P23
	
	!在给定载荷下，计算接触椭圆半轴、趋近量
	IF(BR%SYM) THEN
		!内接触
		p13=POW(BR%BALNO(1)%INN%P,1.0_dp/3.0_DP)
		p23=POW(BR%BALNO(1)%INN%P,2.0_dp/3.0_DP)
		BR%BALNO(:)%INN%AX  =BR%ICOM%AND	*p13
		BR%BALNO(:)%INN%BY  =BR%ICOM%BND	*p13
		BR%BALNO(:)%INN%AB  =BR%BALNO(1)%INN%AX*BR%BALNO(1)%INN%BY
		BR%BALNO(:)%INN%APP =BR%ICOM%APPND	*p23
		!外接触
		p13=POW(BR%BALNO(1)%OUT%P,1.0_dp/3.0_DP)
		p23=POW(BR%BALNO(1)%OUT%P,2.0_dp/3.0_DP)
		BR%BALNO(:)%OUT%AX  =BR%OCOM%AND		*p13
		BR%BALNO(:)%OUT%BY  =BR%OCOM%BND		*p13
		BR%BALNO(:)%OUT%AB  =BR%BALNO(1)%OUT%AX*BR%BALNO(1)%OUT%BY
		BR%BALNO(:)%OUT%APP =BR%OCOM%APPND		*p23

		BR%BALNO(:)%INN%RD=BR%ICOM%RC/BR%BALNO(1)%INN%BY				!RC/B  AXIS B OF CONTACT PATCH 用来计算HERTHCOTE SLIP
		BR%BALNO(:)%OUT%RD=BR%OCOM%RC/BR%BALNO(1)%OUT%BY				!RC/B  AXIS B OF CONTACT PATCH 用来计算HERTHCOTE SLIP
	ELSE
		DO I=1,BR%Z
			!内接触
			BR%BALNO(I)%INN%AX  =BR%ICOM%AND		*POW(BR%BALNO(I)%INN%P,1.0_dp/3.0_DP)
			BR%BALNO(I)%INN%BY  =BR%ICOM%BND		*POW(BR%BALNO(I)%INN%P,1.0_dp/3.0_DP)
			BR%BALNO(I)%INN%AB  =BR%BALNO(I)%INN%AX*BR%BALNO(I)%INN%BY
			BR%BALNO(I)%INN%APP =BR%ICOM%APPND	*POW(BR%BALNO(I)%INN%P,2.0_dp/3.0_DP)
			!外接触
			BR%BALNO(I)%OUT%AX  =BR%OCOM%AND		*POW(BR%BALNO(I)%OUT%P,1.0_dp/3.0_DP)
			BR%BALNO(I)%OUT%BY  =BR%OCOM%BND		*POW(BR%BALNO(I)%OUT%P,1.0_dp/3.0_DP)
			BR%BALNO(I)%OUT%AB  =BR%BALNO(I)%OUT%AX*BR%BALNO(I)%OUT%BY
			BR%BALNO(I)%OUT%APP =BR%OCOM%APPND	*POW(BR%BALNO(I)%OUT%P,2.0_dp/3.0_DP)
		ENDDO
	ENDIF
ENDSUBROUTINE PCHAXIS

SUBROUTINE GETCIJ(BR)
	USE GLOBAL
	USE NR, ONLY:POLIN2
	IMPLICIT NONE
	TYPE(BEARSYSDATA),INTENT(INOUT),TARGET	:: BR
	REAL(DP)::X1A(1:10),X2A(1:3),CIJ(19,13),YA(10,3)
	INTEGER							:: I
	REAL(DP)::DY,KE,NU,C123
	CIJ(:,:)=0.0_DP; YA(:,:)=0.0_DP
	
	OPEN(UNIT=7, file="CSCOES.TXT",POSITION='REWIND',ACTION='READ')
	DO I=1,19
			READ(7,*) CIJ(I,1),CIJ(I,2),CIJ(I,3),CIJ(I,4),CIJ(I,5),CIJ(I,6),CIJ(I,7),CIJ(I,8),CIJ(I,9),CIJ(I,10),CIJ(I,11),CIJ(I,12),CIJ(I,13)
	ENDDO
	CLOSE(7)

	NU=BR%NU1  !或者NU2 均相等
	X2A(1)=0.0_DP;X2A(2)=0.25_DP;X2A(3)=0.5_DP
	!内接触
	KE=MIN(1.0_DP/BR%ICOM%KE,BR%ICOM%KE)
	IF(BR%ICOM%XLARGER==.FALSE.) THEN
		X1A(1:10)=CIJ(1:10,1)
		YA(1:10,1:3)=CIJ(1:10,2:4)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%ICOM%C11=C123
		YA(1:10,1:3)=CIJ(1:10,5:7)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%ICOM%C22=C123
		YA(1:10,1:3)=CIJ(1:10,8:10)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%ICOM%C23= C123
		BR%ICOM%C32=-C123
		YA(1:10,1:3)=CIJ(1:10,11:13)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%ICOM%C33=C123
	ELSE
		X1A(1:10)=CIJ(10:19,1)
		YA(1:10,1:3)=CIJ(10:19,2:4)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%ICOM%C11=C123
		YA(1:10,1:3)=CIJ(10:19,5:7)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%ICOM%C22=C123
		YA(1:10,1:3)=CIJ(10:19,8:10)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%ICOM%C23= C123
		BR%ICOM%C32=-C123
		YA(1:10,1:3)=CIJ(10:19,11:13)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%ICOM%C33=C123
	ENDIF
	!外接触
	KE=MIN(1.0_DP/BR%OCOM%KE,BR%OCOM%KE)
	IF(BR%OCOM%XLARGER==.FALSE.) THEN
		X1A(1:10)=CIJ(1:10,1)
		YA(1:10,1:3)=CIJ(1:10,2:4)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%OCOM%C11=C123
		YA(1:10,1:3)=CIJ(1:10,5:7)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%OCOM%C22=C123
		YA(1:10,1:3)=CIJ(1:10,8:10)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%OCOM%C23= C123
		BR%OCOM%C32=-C123
		YA(1:10,1:3)=CIJ(1:10,11:13)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%OCOM%C33=C123
	ELSE
		X1A(1:10)=CIJ(10:19,1)
		YA(1:10,1:3)=CIJ(10:19,2:4)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%OCOM%C11=C123
		YA(1:10,1:3)=CIJ(10:19,5:7)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%OCOM%C22=C123
		YA(1:10,1:3)=CIJ(10:19,8:10)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%OCOM%C23= C123
		BR%OCOM%C32=-C123
		YA(1:10,1:3)=CIJ(10:19,11:13)
		CALL POLIN2(X1A,X2A,YA,KE,NU,C123,DY)
		BR%OCOM%C33=C123
	ENDIF
ENDSUBROUTINE GETCIJ

SUBROUTINE GETCREEP(BR)
	USE GLOBAL
	IMPLICIT NONE
	TYPE(BEARSYSDATA),INTENT(INOUT),TARGET	:: BR
	INTEGER		:: I
	REAL(DP)	:: P,AX,BY,Z0,XIX,XIY,PSI,RD
	REAL(DP)	:: TEMP,AB

	IF(BR%SYM) THEN
		!外接触
		P =BR%BALNO(1)%OUT%P
		AX=BR%BALNO(1)%OUT%AX
		BY=BR%BALNO(1)%OUT%BY
		AB=BR%BALNO(1)%OUT%AB
		Z0=P/AB/BR%NP
		XIX=BR%BALNO(1)%OUT%XIX
		XIY=BR%BALNO(1)%OUT%XIY
		PSI=BR%BALNO(1)%OUT%PSI

		BR%BALNO(:)%OUT%UX =0.375_DP *XIX*BR%OCOM%C11*BR%G1/BR%MU/Z0
		BR%BALNO(:)%OUT%UY =0.375_DP *XIY*BR%OCOM%C22*BR%G1/BR%MU/Z0
		BR%BALNO(:)%OUT%PHX=4.0_DP*BY*PSI*BR%OCOM%C23*BR%G1/BR%MU/Z0/PI_D/SQRT(BR%OCOM%KE)
		BR%BALNO(:)%OUT%PHY=BR%BALNO(1)%OUT%PHX*BR%OCOM%KE

		RD=BR%BALNO(1)%OUT%RD
		BR%BALNO(:)%OUT%UH=-3.0_DP*AB*BR%NP*BR%G1*BR%OCOM%C11/(16.0_DP*BR%MU*P*RD**2)    !用来计算HERTHCOTE SLIP

	  !内接触
		P =BR%BALNO(1)%INN%P
		AX=BR%BALNO(1)%INN%AX
		BY=BR%BALNO(1)%INN%BY
		AB=BR%BALNO(1)%INN%AB
		Z0=P/AB/BR%NP
		XIX=BR%BALNO(1)%INN%XIX
		XIY=BR%BALNO(1)%INN%XIY
		PSI=BR%BALNO(1)%INN%PSI

		BR%BALNO(:)%INN%UX=0.375_DP*XIX*BR%ICOM%C11*BR%G1/BR%MU/Z0
		BR%BALNO(:)%INN%UY=0.375_DP*XIY*BR%ICOM%C22*BR%G1/BR%MU/Z0
		BR%BALNO(:)%INN%PHX=4.0_DP*BY*PSI*BR%ICOM%C23*BR%G1/BR%MU/Z0/PI_D/SQRT(BR%ICOM%KE) 
		BR%BALNO(:)%INN%PHY=BR%BALNO(1)%INN%PHX*BR%ICOM%KE

		RD=BR%BALNO(1)%INN%RD
		BR%BALNO(:)%INN%UH=-3.0_DP*AB*BR%NP*BR%G1*BR%OCOM%C11/(16.0_DP*BR%MU*P*RD**2)    !用来计算HERTHCOTE SLIP
	ELSE
		!外接触
		DO I=1,BR%Z
			P =BR%BALNO(I)%OUT%P
			AX=BR%BALNO(I)%OUT%AX
			BY=BR%BALNO(I)%OUT%BY
			AB=BR%BALNO(I)%OUT%AB
			Z0=P/AX/BY/BR%NP
			XIX=BR%BALNO(I)%OUT%XIX
			XIY=BR%BALNO(I)%OUT%XIY
			PSI=BR%BALNO(I)%OUT%PSI
			BR%BALNO(I)%OUT%UX=0.375_DP*XIX*BR%OCOM%C11*BR%G1/BR%MU/Z0
			BR%BALNO(I)%OUT%UY=0.375_DP*XIY*BR%OCOM%C22*BR%G1/BR%MU/Z0
			BR%BALNO(I)%OUT%PHX=4.0_DP*BY*PSI*BR%OCOM%C23*BR%G1/BR%MU/Z0/PI_D/SQRT(BR%OCOM%KE) 
			BR%BALNO(I)%OUT%PHY=BR%BALNO(I)%OUT%PHX*BR%OCOM%KE
!			RD=BR%BALNO(I)%OUT%RD
!			BR%BALNO(I)%OUT%UH=-AX*0.5_dp/RD**2/BR%MU/Z0/L1    !用来计算HERTHCOTE SLIP
		ENDDO
		!内接触
		DO I=1,BR%Z
			P =BR%BALNO(I)%INN%P
			AX=BR%BALNO(I)%INN%AX
			BY=BR%BALNO(I)%INN%BY
			AB=BR%BALNO(I)%INN%AB
			Z0=P/AX/BY/BR%NP
			XIX=BR%BALNO(I)%INN%XIX
			XIY=BR%BALNO(I)%INN%XIY
			PSI=BR%BALNO(I)%INN%PSI
			BR%BALNO(I)%INN%UX=0.375_DP*XIX*BR%ICOM%C11*BR%G1/BR%MU/Z0
			BR%BALNO(I)%INN%UY=0.375_DP*XIY*BR%ICOM%C22*BR%G1/BR%MU/Z0
			BR%BALNO(I)%INN%PHX=4.0_DP*BY*PSI*BR%ICOM%C23*BR%G1/BR%MU/Z0/PI_D/SQRT(BR%ICOM%KE) 
			BR%BALNO(I)%INN%PHY=BR%BALNO(I)%INN%PHX*BR%ICOM%KE
!			RD=BR%BALNO(I)%INN%RD
!			BR%BALNO(I)%INN%UH=-AX*0.5_dp/RD**2/BR%MU/Z0/L1    !用来计算HERTHCOTE SLIP
		ENDDO
	ENDIF
ENDSUBROUTINE GETCREEP

SUBROUTINE GETCREEP2(BR)
	USE GLOBAL
	IMPLICIT NONE
	TYPE(BEARSYSDATA),INTENT(INOUT),TARGET	:: BR
	INTEGER		:: I
	REAL(DP)	:: P,AX,BY,Z0,XIX,XIY,PSI,RD
	REAL(DP)	:: TEMP,AB

		!外接触
		P =BR%BALNO(1)%OUT%P
		AX=BR%BALNO(1)%OUT%AX
		BY=BR%BALNO(1)%OUT%BY
		AB=BR%BALNO(1)%OUT%AB
!		Z0=P/AB/BR%NP
		XIX=BR%BALNO(1)%OUT%XIX
		XIY=BR%BALNO(1)%OUT%XIY
		PSI=BR%BALNO(1)%OUT%PSI

		BR%BALNO(:)%OUT%UX=0.375_DP*AB*BR%NP*BR%G1*BR%OCOM%C11*XIX/BR%MU/P
		BR%BALNO(:)%OUT%UY=0.375_DP*AB*BR%NP*BR%G1*BR%OCOM%C22*XIY/BR%MU/P
		BR%BALNO(:)%OUT%PHX=4.0_DP*BY**2*SQRT(AB)*BR%NP*BR%G1*BR%OCOM%C23*PSI/PI_D/BR%MU/P
		BR%BALNO(:)%OUT%PHY=4.0_DP*AB*SQRT(AB)*BR%NP*BR%G1*BR%OCOM%C23*PSI/PI_D/BR%MU/P


	  !内接触
		P =BR%BALNO(1)%INN%P
		AX=BR%BALNO(1)%INN%AX
		BY=BR%BALNO(1)%INN%BY
		AB=BR%BALNO(1)%INN%AB
		Z0=P/AB/BR%NP
		XIX=BR%BALNO(1)%INN%XIX
		XIY=BR%BALNO(1)%INN%XIY
		PSI=BR%BALNO(1)%INN%PSI

		BR%BALNO(:)%INN%UX=0.375_DP*XIX*BR%ICOM%C11*BR%G1/BR%MU/Z0
		BR%BALNO(:)%INN%UY=0.375_DP*XIY*BR%ICOM%C22*BR%G1/BR%MU/Z0
		BR%BALNO(:)%INN%PHX=4.0_DP*BY*PSI*BR%ICOM%C23*BR%G1/BR%MU/Z0/PI_D/SQRT(BR%ICOM%KE) 
		BR%BALNO(:)%INN%PHY=BR%BALNO(1)%INN%PHX*BR%ICOM%KE

ENDSUBROUTINE GETCREEP2

SUBROUTINE GETABK(PCH)
	USE GLOBAL
	USE NR, ONLY:QROMB
	USE INTFACE,ONLY:ELLIP_NEW,POW,FIRSTINTE,SECONDINTE
	IMPLICIT NONE
	TYPE(PATCHABK),INTENT(INOUT),TARGET	:: PCH
	REAL(DP)	::NEWKE,KE,EI1K,EI2E,RDIFF,RX,RY,RSUM,RE
	COMMON /KE/ KE

	!计算X、Y方向上的有效半径（EFFECTIVE RADIUS)
	RX=PCH%RX1*PCH%RX2/(PCH%RX1+PCH%RX2)
	RY=PCH%RY1*PCH%RY2/(PCH%RY1+PCH%RY2)
	RSUM=RX*RY/(RX+RY)
	RDIFF=ABS(RY-RX)/(RX+RY)!计算球综合主曲率差
	RE=2.0_DP/((1.0_DP-PCH%NU1**2)/PCH%E1+(1.0_DP-PCH%NU2**2)/PCH%E2)
	!叠代求解接触椭圆率
	KE=1.0_DP/SQRT(1.0_DP-(MIN(RX,RY)/MAX(RX,RY))**(4.0_DP/3.0_DP))
	WRITE(*,*) KE
	NEWKE=ELLIP_NEW(RDIFF)
	DO WHILE(ABS(NEWKE-KE)>PCH%KP)
		KE=NEWKE
		NEWKE=ELLIP_NEW(RDIFF)
	END DO
	KE=NEWKE
	EI1K=QROMB(FIRSTINTE ,0.0_DP,PIO2_D)
	EI2E=QROMB(SECONDINTE,0.0_DP,PIO2_D)
	!为了计算微积分方程系数的需要，必须使椭圆率在0～1之间
	IF(RX<RY) THEN
		KE=1.0_DP/KE
		PCH%XLARGER=.FALSE.
		!重新计算第一类和第二类椭圆积分值
		EI1K=QROMB(FIRSTINTE ,0.0_DP,PIO2_D)
		EI2E=QROMB(SECONDINTE,0.0_DP,PIO2_D)
	ELSE
		PCH%XLARGER=.TRUE.
	END IF	
	PCH%KE=KE
	!计算干接触工况下接触椭圆半轴长度
	PCH%AND=POW(6.0_DP*(KE**2)*EI2E*RSUM/PI_D/RE,1.0_DP/3.0_DP)
	PCH%BND=POW(6.0_DP*EI2E*RSUM/PI_D/KE/RE,1.0_DP/3.0_DP)
	PCH%APPND=EI1K*POW((9.0_DP/2.0_DP/EI2E/RSUM)*POW(1.0_DP/PI_D/KE/RE,2.0_DP),1.0_DP/3.0_DP) 
	PCH%RE=RE
	PCH%RX=RX
	PCH%RY=RY
	PCH%EI1K=EI1K
	PCH%EI2E=EI2E
ENDSUBROUTINE GETABK


