FUNCTION FUNCV(X,FS,BR)
	USE GLOBAL
	USE NRTYPE
	USE INTFACE,ONLY:RAD2DEG
	IMPLICIT NONE
	REAL(DP), DIMENSION(:), INTENT(IN) :: X
	TYPE(FASTDATA),INTENT(INOUT),TARGET	:: FS
	TYPE(BEARSYSDATA),INTENT(INOUT),TARGET	:: BR
	REAL(DP), DIMENSION(SIZE(X)) :: FUNCV
	CHARACTER(LEN=1)			:: TAB=CHAR(9)
	REAL(DP)	::ALPHA,BETA,ALPHAI,ALPHAO
	REAL(DP)	::OMGI,OMGO
	REAL(DP)	::OMGX,OMGY,OMGZ
	REAL(DP)	::XIXO,XIXI,XIYO,XIYI,PSIO,PSII,E
	REAL(DP)	::NUM,DEMO !局 部变量，分子、分母
	REAL(DP)	::CAI,CAO,SAI,SAO
	REAL(DP)	::TXI,TYI,MXI,MYI,MZI
	REAL(DP)	::TXO,TYO,MXO,MYO,MZO
	REAL(DP)	::MGZ,MGX,FC,P_I,P_O
	REAL(DP)	::DTI,DTO
	REAL(DP)	::RO,RI
	LOGICAL		::OUTER
	INTEGER		::I
	REAL(DP)	::TEMP

	OMGI=BR%OMGI
	OMGO	=X(1)
	OMGX	=X(2)    !
	OMGY	=X(3)
	OMGZ	=X(4)
	ALPHAI=X(5)
	ALPHAO=X(6)
!	P_I		=X(7)
!	P_O		=X(8)

	CAI=COS(ALPHAI)
	SAI=SIN(ALPHAI)
	CAO=COS(ALPHAO)
	SAO=SIN(ALPHAO)

	P_O=(BR%ALOAD/BR%Z+TYO*CAO)/SAO
	P_I=(BR%ALOAD/BR%Z-TYI*CAI)/SAI

	BR%BALNO(:)%INN%P =P_I 
	BR%BALNO(:)%OUT%P =P_O 
	CALL PCHAXIS(BR)

	DTO=BR%BALNO(1)%OUT%APP
	DTI=BR%BALNO(1)%INN%APP

	RO=BR%R-DTO/2.0_DP !接触中心变形后与滚动体中心的距离
	RI=BR%R-DTI/2.0_DP !同上

	E=ABS(BR%ICOM%RX2)+ABS(BR%ICOM%RY2)-(BR%BALNO(1)%AI+BR%BALNO(1)%INN%APP)*CAI

	TEMP=OMGY*CAO+OMGZ*SAO
	NUM	= E*OMGO-RO*(TEMP-OMGO*CAO)
	DEMO=(E*OMGO+RO*(TEMP+OMGO*CAO))/2.0_DP		!	DEMO=OMGO*(E+RO*CAO)!	DEMO=RO*TEMP	
	XIXO=NUM/DEMO
	NUM	=RO*OMGX   
	XIYO=NUM/DEMO
	NUM	=SQRT(BR%BALNO(1)%OUT%AB)*(OMGZ*CAO-OMGY*SAO+OMGO*SAO)
	PSIO=NUM/DEMO

BR%BALNO(:)%OUT%R2S=(OMGZ*CAO-OMGY*SAO+OMGO*SAO)/(TEMP-OMGO*CAO)		!ROLL TO SPIN RATIO


	TEMP=OMGY*CAI+OMGZ*SAI
	NUM = OMGI*E-RI*(TEMP+OMGI*CAI)
	DEMO=(OMGI*E+RI*(TEMP-OMGI*CAI))/2.0_DP		!DEMO=OMGI*(E-RI*CAI)!	DEMO=RI*TEMP	
	XIXI=NUM/DEMO
	NUM =-RI*OMGX  
	XIYI=NUM/DEMO
	NUM	=SQRT(BR%BALNO(1)%INN%AB)*(OMGY*SAI-OMGZ*CAI+OMGI*SAI)
	PSII=NUM/DEMO

BR%BALNO(:)%INN%R2S=(OMGY*SAI-OMGZ*CAI+OMGI*SAI)/(TEMP+OMGI*CAI)		!ROLL TO SPIN RATIO

WRITE(*,*) PSIO,PSII
!WRITE(*,*)


	BR%BALNO(:)%OUT%XIX=XIXO
	BR%BALNO(:)%OUT%XIY=XIYO
	BR%BALNO(:)%OUT%PSI=PSIO
	BR%BALNO(:)%INN%XIX=XIXI
	BR%BALNO(:)%INN%XIY=XIYI
	BR%BALNO(:)%INN%PSI=PSII
	CALL GETCREEP(BR)		!计算FASTSIM所需的各种参数

	!循环计算接触拖动力
	DO I=1,BR%CYC
		OUTER=.TRUE.
		CALL PREFS(FS,BR,I,OUTER)  
		CALL FASTSIM(FS)
		CALL  POSTFS(FS,BR,I,OUTER)
		OUTER=.FALSE.
		CALL PREFS(FS,BR,I,OUTER)
		CALL FASTSIM(FS)
		CALL POSTFS(FS,BR,I,OUTER)
	ENDDO 

	TXO=BR%BALNO(1)%OUT%TX
	TYO=BR%BALNO(1)%OUT%TY
	MXO=BR%BALNO(1)%OUT%MX
	MYO=BR%BALNO(1)%OUT%MY
	MZO=BR%BALNO(1)%OUT%MZ

	TXI=BR%BALNO(1)%INN%TX
	TYI=BR%BALNO(1)%INN%TY
	MXI=BR%BALNO(1)%INN%MX
	MYI=BR%BALNO(1)%INN%MY
	MZI=BR%BALNO(1)%INN%MZ

	FC =0.0_DP !不考虑离心力
!	FC =br%aload/br%z !不考虑离心力
	MGX=0.0_DP*220 !不考虑陀螺力矩
	MGZ=0.0_DP !不考虑陀螺力矩
!	FC =BR%M1*E*(OMGO**2.0_DP)

!	MGX=BR%IP*OMGz*OMGO
!	MGX=1.0E-3_DP
!	MGZ=BR%IP*OMGx*OMGO

	!控制字段
	BR%CONSTT=1.0E0_DP

	FUNCV(1)=BR%CONSTT*(MXO-MXI-MGX)
	FUNCV(2)=BR%CONSTT*(-MZO*CAO+MZI*CAI-MYI*SAI-MYO*SAO+MGZ +MZO*SAO-MZI*SAI-MYI*CAI-MYO*CAO)
	FUNCV(3)=BR%CONSTT*(TXO-TXI)
	FUNCV(4)=BR%CONSTT*(-P_O*CAO+P_I*CAI-TYO*SAO-TYI*SAI+FC)
	FUNCV(5)=BR%CONSTT*(TXI*(E-RI*CAI)+MZI*SAI-TXO*(E+RO*CAO)-MZO*SAO) 
	FUNCV(6)=((BR%BALNO(1)%AO+DTO)*CAO+(BR%BALNO(1)%AI+DTI)*CAI)/(BR%BALNO(1)%A*COS(BR%BALNO(1)%OUT%ALPHA0))-1.0_DP

!	FUNCV(7)=BR%CONSTT*(BR%ALOAD/BR%Z-P_O*SAO+TYO*CAO)
!	FUNCV(8)=BR%CONSTT*(BR%ALOAD/BR%Z-P_I*SAI-TYI*CAI)
!WRITE(6,"(E23.15,A1,E23.15,A1,E23.15,A1,E23.15,A1,E23.15,A1,E23.15,A1,E23.15,A1,E23.15)")  &
!	OMGO,TAB,OMGB,TAB,ALPHA,TAB,BETA,TAB,ALPHAI,TAB,ALPHAO,TAB,P_I,TAB,P_O
!	X(1),TAB,X(2),TAB,X(3),TAB,X(4),TAB,X(5),TAB,X(6),TAB,X(7),TAB,X(8)
!	TXI,TAB,TYI,TAB,xiyo,TAB,xiyi,TAB,psio,TAB,psii,TAB,FUNCV(6),TAB,FUNCV(8)
ENDFUNCTION FUNCV

SUBROUTINE SOLVE(FS,BR)
	USE GLOBAL
	USE NRTYPE
	USE NR
	USE INTFACE,ONLY:RAD2DEG,POW
	IMPLICIT NONE
	INTERFACE
		FUNCTION FUNCV(X,FS,BR)
		USE GLOBAL
		USE NRTYPE
		IMPLICIT NONE
		REAL(DP), DIMENSION(:), INTENT(IN) :: X
		TYPE(FASTDATA),INTENT(INOUT),TARGET	:: FS
		TYPE(BEARSYSDATA),INTENT(INOUT),TARGET	:: BR
		REAL(DP), DIMENSION(SIZE(X)) :: FUNCV
		END FUNCTION FUNCV
	END INTERFACE
	TYPE(FASTDATA),INTENT(INOUT),TARGET	:: FS
	TYPE(BEARSYSDATA),INTENT(INOUT),TARGET	:: BR
	INTEGER(I4B), PARAMETER :: N=6   !未知量个数
	INTEGER(I4B) :: I,J,k
	REAL(DP), DIMENSION(N) :: X,F
	LOGICAL(LGT) :: CHECK
	REAL(DP) ::GAMA,EST,UIST,UOST,GAMAP
	REAL(DP) ::OMGO,OMGB
	REAL(DP)	::OMU


!	OPEN(6, FILE="TEST.XLS")  !创建数据文件 EXCEL文件
	!JONES方法计算初值
	UIST=BR%ICOM%APPND*POW(BR%BALNO(1)%INN%P,2.0_dp/3.0_DP)/2.0_DP
	UOST=BR%OCOM%APPND*POW(BR%BALNO(1)%OUT%P,2.0_dp/3.0_DP)/2.0_DP
	EST=ABS(BR%ICOM%RX2)+ABS(BR%ICOM%RY2)-(BR%BALNO(1)%AI+UIST*2.0_DP)*COS(BR%BALNO(1)%INN%ALPHAST)
	OMGB=BR%OMGI*(EST-(BR%R-UIST)*COS(BR%BALNO(1)%INN%ALPHAST))/(BR%R-UIST)
	OMGO=OMGB*(BR%R-UOST)/(EST+(BR%R-UOST)*COS(BR%BALNO(1)%INN%ALPHAST))

	!HARRIS方法计算初值
	GAMA=BR%D*COS(BR%BALNO(1)%OUT%ALPHAST)*2.0_DP/(BR%D_I+BR%D_O)		!计算
	GAMAP=BR%D*2.0_DP/(BR%D_I+BR%D_O)																!
BR%BALNO(:)%OUT%R2S=GAMAP*SIN(BR%BALNO(1)%OUT%ALPHAST)
write(*,*) BR%BALNO(1)%OUT%R2S
!	X(1)=BR%OMGI*(1.0_DP-GAMA)/(1.0_DP+GAMA)  !HARRIS理论 
!	X(2)=BR%OMGI*BR%DM/BR%D*(1.0_DP-GAMA) !HARRIS理论	
	X(1)=OMGO
	X(2)=-0.000001_dp
	X(3)=OMGB*COS(BR%BALNO(1)%INN%ALPHAST)
	X(4)=OMGB*SIN(BR%BALNO(1)%INN%ALPHAST)   
	X(5)=BR%BALNO(1)%INN%ALPHAST
	X(6)=BR%BALNO(1)%OUT%ALPHAST
!	X(7)=BR%BALNO(1)%INN%P
!	X(8)=BR%BALNO(1)%OUT%P

	J=0
	DO J=1,1
		BR%MU=BR%MU*1.0_DP
		WRITE(*,*) BR%MU
		K=0
		CHECK=.TRUE.
		DO WHILE(CHECK .AND. K<3)
			CALL BROYDN(X,CHECK,FS,BR)		!; WRITE(*,*) "BY BROYDN"
!			CALL NEWT(X,CHECK,FS,BR); WRITE(*,*) "BY NEWT"
			F=FUNCV(X,FS,BR)
			IF(CHECK) WRITE(*,*) 'CONVERGENCE PROBLEMS: NOT CONVERGED?!'
			WRITE(*,*) '        INDEX','          X','                     F'
			DO I=1,N
				WRITE(*,*) I,X(I),F(I)
			END DO
			K=K+1
		ENDDO
		IF(CHECK) PAUSE
	ENDDO

	BR%BALNO(:)%ALPHA				=X(3)
	BR%BALNO(:)%BETA				=X(4)
	BR%BALNO(:)%INN%ALPHA		=X(5)
	BR%BALNO(:)%OUT%ALPHA		=X(6)

WRITE(*,*) BR%ICOM%KE,BR%OCOM%KE
!	CLOSE(6)
WRITE(*,*) "STATIC CONTACT ANG:",BR%BALNO(1)%INN%ALPHAST,RAD2DEG(BR%BALNO(1)%INN%ALPHAST)
WRITE(*,*) "  FREE CONTACT ANG:",BR%BALNO(1)%INN%ALPHA0 ,RAD2DEG(BR%BALNO(1)%INN%ALPHA0)
WRITE(*,*) "NO SLIP OMGO:",OMGO,BR%OMGI*(1.0_DP-GAMA)/(1.0_DP+GAMA)
WRITE(*,*) "NO SLIP OMGB:",OMGB,BR%OMGI*BR%DM/BR%D*(1.0_DP-GAMA)
ENDSUBROUTINE SOLVE


