!THE SUBROUTINES AFTERWARDS ARE THE ELLIPTICAL INTEGRALS 
!THAT MIGHT BE USED IN CALCULATION
FUNCTION FIRSTINTE(X)
	USE FSBR
	IMPLICIT NONE
	REAL(DP), DIMENSION(:), INTENT(IN) :: X
	REAL(DP), DIMENSION(SIZE(X)) :: FIRSTINTE
	REAL(DP)	::KE
	COMMON	/KE/ KE
	FIRSTINTE=1.0_DP/SQRT(1.0_DP-(1.0_DP-1.0_DP/KE/KE)*SIN(X)*SIN(X))
END FUNCTION FIRSTINTE

FUNCTION SECONDINTE(X)
	USE FSBR
	IMPLICIT NONE
	REAL(DP), DIMENSION(:), INTENT(IN) :: X
	REAL(DP), DIMENSION(SIZE(X)) :: SECONDINTE
	REAL(DP)	::KE
	COMMON	/KE/ KE
	SECONDINTE=SQRT(1.0_DP-(1.0_DP-1.0_DP/KE/KE)*SIN(X)*SIN(X))
END FUNCTION SECONDINTE

FUNCTION ELLIP_NEW(RDIFF)
	USE FSBR
	USE INTFACE,ONLY:FIRSTINTE,SECONDINTE
	USE NR, ONLY:QROMB
	IMPLICIT NONE
	REAL(DP) :: ELLIP_NEW	,KE
	REAL(DP) ::	TEMP,K,E
	REAL(DP) ::	RDIFF
	K=QROMB(FIRSTINTE ,0.0_DP,PIO2_D)
	E=QROMB(SECONDINTE,0.0_DP,PIO2_D)
	!计算公式加绝对值，否则无法进行开方，不知道为什么
	ELLIP_NEW=SQRT(ABS((2.0_DP*K-E*(1.0_DP+RDIFF))/(E*(1.0_DP-RDIFF))))
END FUNCTION ELLIP_NEW

FUNCTION POW(BASE,EXPO)
	USE FSBR
	IMPLICIT NONE
	REAL(DP),INTENT(IN)	:: BASE,EXPO
	REAL(DP)			:: POW
	POW=BASE**EXPO
END FUNCTION POW

SUBROUTINE FUNCD(X,FVAL,FDERIV)
	USE FSBR
	USE NRTYPE
	use nr
	USE INTFACE,ONLY:POW
	IMPLICIT NONE
	REAL(DP), INTENT(IN) :: X
	REAL(DP), INTENT(OUT) :: FVAL,FDERIV
	
	REAL(DP) ::FA,A,KN,ALf0
	INTEGER	 ::Z
	real(dp)	:: dy

	FA=BR%ALOAD
	Z	=BR%Z
	A	=BR%A
	ALf0=BR%ALf0
	call ratint(br%alf,br%kn,x,kn,dy)
	FVAL=POW(FA/Z/KN/POW(A,1.5_DP),2.0_DP)-SIN(X)**2*POW(COS(ALf0)/COS(X)-1.0_DP,3.0_DP)
	FDERIV=-POW(COS(ALf0)/COS(X)-1.0_DP,2.0_DP)*(SIN(2*X)*(COS(ALf0)/COS(X)-1.0_DP)+3.0_DP*POW(TAN(X),3.0_DP)*COS(X)*COS(ALf0))
!	FDERIV=-SIN(2*X)*POW(COS(ALf0)/COS(X)-1.0_DP,3.0_DP)-3.0_DP*(SIN(X)**3)/(COS(X)**2)*COS(ALf0)*POW(COS(ALf0)/COS(X)-1.0_DP,2.0_DP)

ENDSUBROUTINE FUNCD

FUNCTION RAD2DEG(RAD)
	use nrtype
	IMPLICIT NONE
	REAL(DP),INTENT(IN)	:: RAD
	REAL(DP)			:: RAD2DEG
	RAD2DEG=RAD*180._DP/PI_D
END FUNCTION RAD2DEG

FUNCTION DEG2RAD(deg)
	use nrtype
	IMPLICIT NONE
	REAL(DP),INTENT(IN)	:: deg
	REAL(DP)			:: DEG2RAD
	DEG2RAD=deg*PI_D/180._DP
END FUNCTION DEG2RAD

FUNCTION REV2RAD(rev)
	use nrtype
	IMPLICIT NONE
	REAL(DP),INTENT(IN)	:: rev
	REAL(DP)			:: REV2RAD
	REV2RAD=rev*2.0_dp*pi_d/60.0_dp
END FUNCTION REV2RAD

FUNCTION RAD2REV(rad)
	use nrtype
	IMPLICIT NONE
	REAL(DP),INTENT(IN)	:: rad
	REAL(DP)			:: RAD2REV
	RAD2REV=rad/2.0_dp/pi_d*60.0_dp
END FUNCTION RAD2REV












!SUBROUTINE ELLIPINT()
!	USE GLOBAL
!	USE INTFACE
!	USE NR, ONLY:QROMB
!	IMPLICIT NONE
!	REAL(DP):: K,E,B,C,D,E2,SIGMA
!	KE=0.1
!	E2=1.0_DP-KE*KE
!	K=QROMB(EI1ST,0.0_DP,PIO2_D)
!	E=QROMB(EI2ND,0.0_DP,PIO2_D)
!	B=(E-(1.0_DP-E2)*K)/E2
!	C=((2.0_DP-E2)*K-2.0_DP*E)/E2**2
!	D=(K-E)/E2
!	WRITE(*,*) K ,E
!	WRITE(*,*) B
!	WRITE(*,*) C,D
!	SIGMA=0.0_DP
!WRITE(*,*) 2.51/4.0_DP*(4.0_DP-SIGMA)*PI_D/16.0_DP/(B-SIGMA*(1-E2)*C)
!ENDSUBROUTINE ELLIPINT
!
!FUNCTION EI1ST(X)
!	USE GLOBAL
!	IMPLICIT NONE
!	REAL(DP), DIMENSION(:), INTENT(IN) :: X
!	REAL(DP), DIMENSION(SIZE(X)) :: EI1ST
!	REAL(DP)	:: G,E2
!	G=MIN(KE,1.0_DP/KE)
!	E2=1.0_DP-G*G
!	EI1ST=1.0_DP/SQRT(1.0_DP-E2*SIN(X)*SIN(X))
!END FUNCTION EI1ST
!
!FUNCTION EI2ND(X)
!	USE GLOBAL
!	IMPLICIT NONE
!	REAL(DP), DIMENSION(:), INTENT(IN) :: X
!	REAL(DP), DIMENSION(SIZE(X)) :: EI2ND
!	REAL(DP)	:: G,E2
!	G=MIN(KE,1.0_DP/KE)
!	E2=1.0_DP-G*G
!	EI2ND=SQRT(1.0_DP-E2*SIN(X)*SIN(X))
!END FUNCTION EI2ND
!
!
!