	SUBROUTINE NEWT(X,CHECK)
	USE NRTYPE; USE NRUTIL, ONLY : NRERROR,VABS
	USE NR, ONLY : FDJAC,LNSRCH,LUBKSB,LUDCMP
	USE FMINLN
	IMPLICIT NONE
	REAL(DP), DIMENSION(:), INTENT(INOUT) :: X
	LOGICAL(LGT), INTENT(OUT) :: CHECK
	INTEGER(I4B), PARAMETER :: MAXITS=200
	REAL(DP), PARAMETER :: TOLF=1.0E-12_DP,TOLMIN=1.0E-12_DP,TOLX=EPSILON(X),&
		STPMX=100.0
	INTEGER(I4B) :: ITS
	INTEGER(I4B), DIMENSION(SIZE(X)) :: INDX
	REAL(DP) :: D,F,FOLD,STPMAX
	REAL(DP), DIMENSION(SIZE(X)) :: G,P,XOLD
	REAL(DP), DIMENSION(SIZE(X)), TARGET :: FVEC
	REAL(DP), DIMENSION(SIZE(X),SIZE(X)) :: FJAC
	FMIN_FVECP=>FVEC
	F=FMIN(X)
	IF (MAXVAL(ABS(FVEC(:))) < 0.01_DP*TOLF) THEN
		CHECK=.FALSE.
		RETURN
	END IF
	STPMAX=STPMX*MAX(VABS(X(:)),REAL(SIZE(X),DP))
	DO ITS=1,MAXITS
		CALL FDJAC(X,FVEC,FJAC)
		G(:)=MATMUL(FVEC(:),FJAC(:,:))
		XOLD(:)=X(:)
		FOLD=F
		P(:)=-FVEC(:)
		CALL LUDCMP(FJAC,INDX,D)
		CALL LUBKSB(FJAC,INDX,P)
		CALL LNSRCH(XOLD,FOLD,G,P,X,F,STPMAX,CHECK,FMIN)
		IF (MAXVAL(ABS(FVEC(:))) < TOLF) THEN
			CHECK=.FALSE.
			RETURN
		END IF
		IF (CHECK) THEN
			CHECK=(MAXVAL(ABS(G(:))*MAX(ABS(X(:)),1.0_DP) / &
				MAX(F,0.5_DP*SIZE(X))) < TOLMIN)
			RETURN
		END IF
		IF (MAXVAL(ABS(X(:)-XOLD(:))/MAX(ABS(X(:)),1.0_DP)) < TOLX) &
			RETURN
	END DO
	CALL NRERROR('MAXITS EXCEEDED IN NEWT')
	END SUBROUTINE NEWT
