SUBROUTINE PRINT_FIELD()
	USE FSBR
	IMPLICIT NONE
	REAL(DP),POINTER	:: XC(:,:),YC(:,:)
	REAL(DP),POINTER  :: V(:,:)
	INTEGER	:: I,J,NX,NY
		REAL(DP)::AX,BY
	
	WRITE(*,*) "......WRITING DATA FILE FIELD_DISTRIBUTION.dat......"
	NX=FS%NX
	NY=FS%NY
	XC=>FS%XC
	YC=>FS%YC
	V =>FS%Tx
	OPEN(6, file="FIELD_DISTRIBUTION.dat")  !创建数据文件
	!将数据输出到TECPLOT格式的数据文件
	WRITE(6,*) "TITLE = ""DISTRIBUTION"""
	WRITE(6,*) "VARIABLES = ""X"",""Y"",""DISTRIBUTION"""
	WRITE(6,*) "ZONE T=""DISTRIBUTION"""
	WRITE(6,"(' I=',I5,', J=',I5,', K=1',', ZONETYPE=Ordered')") 2*(NX+1),2*(NY+1)
	WRITE(6,*) "DATAPACKING=BLOCK"
	WRITE(6,*) "DT=(DOUBLE DOUBLE DOUBLE )"

		IF(BR%unscl) THEN
			IF(BR%OPTIN) THEN
				AX=BR%BALNO(1)%INN%AX
				BY=BR%BALNO(1)%INN%BY
			ELSE
				AX=BR%BALNO(1)%OUT%AX
				BY=BR%BALNO(1)%OUT%BY
			ENDIF
		ELSE
			AX=1.0_DP
			BY=1.0_DP
		ENDIF
	!PRINT X COORDINATE
	DO I=-NY-1,NY+1
		DO J=-NX-1,NX+1
			IF(I/=0 .AND. J/=0) WRITE(6,*) XC(I,J)*AX+br%xtran*AX
		ENDDO
	ENDDO
	!PRINT Y COORDINATE
	DO I=-NY-1,NY+1
		DO J=-NX-1,NX+1
			IF(I/=0 .AND. J/=0) WRITE(6,*) YC(I,J)*BY
		ENDDO
	ENDDO
	!PRINT Z 
	DO I=-NY-1,NY+1
		DO J=-NX-1,NX+1
			IF(I/=0 .AND. J/=0) WRITE(6,*) V(I,J)
		ENDDO
	ENDDO

	CLOSE(6)
	WRITE(*,*) "......WRITING FINISHED......"
ENDSUBROUTINE PRINT_FIELD

SUBROUTINE PRINT_TFIELD()
		USE FSBR
		IMPLICIT NONE
		REAL(DP),POINTER :: XC(:,:),YC(:,:),TX(:,:),TY(:,:)
		INTEGER			     :: NX,NY,I,J
		REAL(DP)::AX,BY

	WRITE(*,*) "......WRITING DATA FILE VECTOR_TRAC.dat......"
		NX=FS%NX
		NY=FS%NY
		XC=>FS%XC
		YC=>FS%YC
		TX=>FS%TX
		TY=>FS%TY
		OPEN(6, file="VECTOR_TRAC.dat")  !创建数据文件
		!将数据输出到TECPLOT格式的数据文件
		WRITE(6,*) "TITLE = ""VECTOR FIELD"""
		WRITE(6,*) "VARIABLES = ""X"",""Y"",""UX"",""UY"""
		WRITE(6,*) "ZONE T=""VECTOR FIELD"""
		WRITE(6,"(' I=',I5,', J=',I5,', K=1',', ZONETYPE=Ordered')") 2*(NX+1),2*(NY+1)
		WRITE(6,*) "DATAPACKING=BLOCK"
		WRITE(6,*) "DT=(DOUBLE DOUBLE DOUBLE DOUBLE)"

		IF(BR%unscl) THEN
			IF(BR%OPTIN) THEN
				AX=BR%BALNO(1)%INN%AX
				BY=BR%BALNO(1)%INN%BY
			ELSE
				AX=BR%BALNO(1)%OUT%AX
				BY=BR%BALNO(1)%OUT%BY
			ENDIF
		ELSE
			AX=1.0_DP
			BY=1.0_DP
		ENDIF
		!PRINT X COORDINATE
		DO I=-NY-1,NY+1
			DO J=-NX-1,NX+1
				IF(I/=0 .AND. J/=0) WRITE(6,*) XC(I,J)*AX+br%xtran*AX
			ENDDO
		ENDDO
		!PRINT Y COORDINATE
		DO I=-NY-1,NY+1
			DO J=-NX-1,NX+1
				IF(I/=0 .AND. J/=0) WRITE(6,*) YC(I,J)*BY
			ENDDO
		ENDDO
		!PRINT X COMPONENT OF THE VECTOR TO BE OUTPUT
		DO I=-NY-1,NY+1
			DO J=-NX-1,NX+1
				IF(I/=0 .AND. J/=0) WRITE(6,*) TX(I,J)
			ENDDO
		ENDDO
		!PRINT Y COMPONENT OF THE VECTOR TO BE OUTPUT
		DO I=-NY-1,NY+1
			DO J=-NX-1,NX+1
				IF(I/=0 .AND. J/=0) WRITE(6,*) TY(I,J)
			ENDDO
		ENDDO
	CLOSE(6)
	WRITE(*,*) "......WRITING FINISHED......"
ENDSUBROUTINE PRINT_TFIELD

SUBROUTINE PRINT_SFIELD()
		USE FSBR
		IMPLICIT NONE
		REAL(DP),POINTER :: XC(:,:),YC(:,:),VX(:,:),VY(:,:)
		INTEGER			     :: NX,NY,I,J
		REAL(DP)::AX,BY

	WRITE(*,*) "......WRITING DATA FILE VECTOR_SLIP.dat......"
		NX=FS%NX
		NY=FS%NY
		XC=>FS%XC
		YC=>FS%YC
		VX=>FS%SX
		VY=>FS%SY
		OPEN(6, file="VECTOR_SLIP.dat")  !创建数据文件
		!将数据输出到TECPLOT格式的数据文件
		WRITE(6,*) "TITLE = ""VECTOR FIELD"""
		WRITE(6,*) "VARIABLES = ""X"",""Y"",""SX"",""SY"""
		WRITE(6,*) "ZONE T=""VECTOR FIELD"""
		WRITE(6,"(' I=',I5,', J=',I5,', K=1',', ZONETYPE=Ordered')") 2*(NX+1),2*(NY+1)
		WRITE(6,*) "DATAPACKING=BLOCK"
		WRITE(6,*) "DT=(DOUBLE DOUBLE DOUBLE DOUBLE)"

		IF(BR%unscl) THEN
			IF(BR%OPTIN) THEN
				AX=BR%BALNO(1)%INN%AX
				BY=BR%BALNO(1)%INN%BY
			ELSE
				AX=BR%BALNO(1)%OUT%AX
				BY=BR%BALNO(1)%OUT%BY
			ENDIF
		ELSE
			AX=1.0_DP
			BY=1.0_DP
		ENDIF
		!PRINT X COORDINATE
		DO I=-NY-1,NY+1
			DO J=-NX-1,NX+1
				IF(I/=0 .AND. J/=0) WRITE(6,*) XC(I,J)*AX+br%xtran*AX
			ENDDO
		ENDDO
		!PRINT Y COORDINATE
		DO I=-NY-1,NY+1
			DO J=-NX-1,NX+1
				IF(I/=0 .AND. J/=0) WRITE(6,*) YC(I,J)*BY
			ENDDO
		ENDDO
		WRITE(6,*) !输出空行
		!PRINT X COMPONENT OF THE VECTOR TO BE OUTPUT
		DO I=-NY-1,NY+1
			DO J=-NX-1,NX+1
				IF(I/=0 .AND. J/=0) WRITE(6,*) VX(I,J)
			ENDDO
		ENDDO
		WRITE(6,*) !输出空行
		!PRINT Y COMPONENT OF THE VECTOR TO BE OUTPUT
		DO I=-NY-1,NY+1
			DO J=-NX-1,NX+1
				IF(I/=0 .AND. J/=0) WRITE(6,*) VY(I,J)
			ENDDO
		ENDDO
	CLOSE(6)
	WRITE(*,*) "......WRITING FINISHED......"
ENDSUBROUTINE PRINT_SFIELD

SUBROUTINE VECTOR_COMBINING()
	USE FSBR
	IMPLICIT NONE
	REAL(DP),POINTER :: XC(:,:),YC(:,:),TX(:,:),TY(:,:)
	INTEGER			     :: NX,NY,I,J

	NX=FS%NX
	NY=FS%NY
	TX=>FS%TX
	TY=>FS%TY
	DO I=-NY-1,NY+1
		DO J=-NX-1,NX+1
			IF(I/=0 .AND. J/=0) TX(I,J)=SQRT(TX(I,J)**2+TY(I,J)**2)
		ENDDO
	ENDDO
ENDSUBROUTINE VECTOR_COMBINING

!输出EXCEL文件
!简易保留格式
SUBROUTINE OP()
	USE FSBR
	IMPLICIT NONE
		INTEGER			::NX,NY
	INTEGER :: I,J
	CHARACTER(len=1)			:: tab=CHAR(9)
	OPEN(6, file="TRACTION.XLS")  !创建数据文件 EXCEL文件
	NX=FS%NX
	NY=FS%NY
	DO I=-NY,NY
	IF(I/=0) THEN
	WRITE(6,*) 
	DO J=-NX,NX
		IF(J/=0) THEN
!			WRITE(6,"(e23.15,A1,\)") TRACTX(I,J),TAB
		ENDIF
	ENDDO
	ENDIF
	ENDDO
ENDSUBROUTINE OP
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

