SUBROUTINE SLV14_ALCON2()
	USE FSBR
	USE nrtype
	IMPLICIT NONE
	INTEGER,PARAMETER	::N=6
	REAL(DP)					:: X(N),XW(N),RWORK(7*N**2+35*N+24),IWORK(3*N+2+10)
	INTEGER						:: INFO(9)
	REAL(DP)					:: TAU,TAUMIN,TAUMAX
	REAL(DP)					:: EPS
  EXTERNAL FT,JTEST
  INTEGER UPR,UDIAG,UBIF,UMAX
	INTEGER						:: LRW,LIW
  COMMON /UNIT/ UPR,UDIAG

	WRITE(*,*)'         ***********************************************************'
	WRITE(*,*)'         ***************     BY ALCON1 SUBROUTINE   ****************'
	WRITE(*,*)'         ***********************************************************'

  UPR=6
  UDIAG=2
  LRW=7*N**2+35*N+24
  LIW=3*N+2+10

	CALL X0VCT(X)
	XW(:)=1.0_DP

	TAU=BR%MU
	TAUMIN=TAU
	TAUMAX=TAU+1.0E-4_DP

  UMAX=0.0_DP
  EPS=1.0E-8_DP
	INFO(1)=2
	INFO(2)=999
	INFO(3)=1
	INFO(4)=1
  CALL ALCON2(FT,JTEST,N,X,XW,TAU,TAUMIN,TAUMAX,UMAX,EPS,INFO,&
    RWORK,LRW,IWORK,LIW)

	CALL FT(X,TAUMAX,XW)
	CALL PRINTXF(X,XW)
END

SUBROUTINE FT(X,TAU,F)
	USE FSBR
	USE NRTYPE
	IMPLICIT none
	REAL(DP)	:: X(6),F(6)
	REAL(DP)	:: tau

	BR%MU=TAU
	CALL SLV6EQS(X,F,.false.)
END

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
SUBROUTINE JTEST(X,TAU,DFDX,DFDTAU)
	USE FSBR
	USE NRTYPE
	IMPLICIT none
		REAL(DP), DIMENSION(6)		:: x
		REAL(DP), DIMENSION(6,6)	:: DFDX
		REAL(DP), DIMENSION(6)		:: DFDTAU
	REAL(DP)	:: tau
	REAL(DP)	:: FVEC(6)

	CALL FT(X,TAU,FVEC)
	CALL FDJACA(X,TAU,FVEC,DFDX)
	CALL DFDMU(X,TAU,FVEC,DFDTAU)
END

SUBROUTINE FDJACA(X,TAU,FVEC,DF)
	USE FSBR
	USE NRTYPE; USE NRUTIL, ONLY : ASSERT_EQ
	IMPLICIT NONE
	REAL(DP), DIMENSION(6), INTENT(IN) :: FVEC
	REAL(DP), DIMENSION(6), INTENT(INOUT) :: X
	REAL(DP)				:: TAU
	REAL(DP), DIMENSION(6,6), INTENT(OUT) :: DF
	INTERFACE
		FUNCTION FVT(X,TAU)
		USE FSBR
		USE NRTYPE
		IMPLICIT NONE
		REAL(DP), DIMENSION(:), INTENT(IN) :: X
		REAL(DP)	:: TAU
		REAL(DP), DIMENSION(SIZE(X)) :: FVT
		END FUNCTION FVT
	END INTERFACE
	REAL(DP) :: EPS
	INTEGER(I4B) :: J,N
	REAL(DP), DIMENSION(SIZE(X)) :: XSAV,XPH,H
	N=ASSERT_EQ(SIZE(X),SIZE(FVEC),SIZE(DF,1),SIZE(DF,2),'FDJAC')

	EPS=SQMPREC

	XSAV=X
	H=EPS*ABS(XSAV)
	WHERE (H == 0.0_DP) H=EPS
	XPH=XSAV+H
	H=XPH-XSAV
	DO J=1,N
		X(J)=XPH(J)
		DF(:,J)=(FVT(X,TAU)-FVEC(:))/H(J)
		X(J)=XSAV(J)
	END DO
END SUBROUTINE FDJACA

FUNCTION FVT(X,TAU)
	USE FSBR
	USE NRTYPE
	IMPLICIT NONE
	REAL(DP), DIMENSION(:), INTENT(IN) :: X
	REAL(DP)		:: TAU
	REAL(DP), DIMENSION(SIZE(X)) :: FVT
	REAL(DP)	::F(SIZE(X))
	INTEGER		::I
	
	CALL FT(X,TAU,F)
	FVT=F
ENDFUNCTION FVT

SUBROUTINE DFDMU(X,TAU,FVEC,DF)
	USE FSBR
	USE NRUTIL, ONLY : ASSERT_EQ
	USE INTFACE,ONLY:FUNCV
	IMPLICIT NONE
	INTERFACE
		FUNCTION FVT(X,TAU)
		USE FSBR
		USE NRTYPE
		IMPLICIT NONE
		REAL(DP), DIMENSION(:), INTENT(IN) :: X
		REAL(DP)	:: TAU
		REAL(DP), DIMENSION(SIZE(X)) :: FVT
		END FUNCTION FVT
	END INTERFACE
	REAL(DP), DIMENSION(6), INTENT(IN) :: FVEC
	REAL(DP), DIMENSION(6), INTENT(INOUT) :: X
	REAL(DP), INTENT(INOUT)				:: TAU
	REAL(DP), DIMENSION(6), INTENT(OUT) :: DF
	REAL(DP) :: EPS
	REAL(DP) ::H

	EPS=SQMPREC

	H=EPS*ABS(TAU)
	IF(H == 0.0_DP) H=EPS
	BR%MU=TAU+H
	H=BR%MU-TAU

	DF(:)=(FVT(X,TAU)-FVEC(:))/H

END SUBROUTINE DFDMU

