SUBROUTINE SLV25_NLEQSLV()
	INCLUDE 'CXML_INCLUDE.F90'
	IMPLICIT NONE

  INTEGER,PARAMETER ::N=6
	INTEGER,PARAMETER ::QRWSIZ=1000
	INTEGER,PARAMETER ::LRWORK=9*N+2*N*N

	INTEGER JACFLG,MAXIT,NJCNT,NFCNT,TERMCD,METHOD
  INTEGER GLOBAL,XSCALM
  INTEGER OUTOPT(N)
  DOUBLE PRECISION  XTOL,FTOL,BTOL,STEPMX,DLT,SIGMA
  DOUBLE PRECISION  XP(N),FP(N),GP(N),X0(N)
  DOUBLE PRECISION  RWORK(LRWORK),RCDWRK(3*N),QRWORK(QRWSIZ)
  DOUBLE PRECISION  SCALEX(N)         
  INTEGER           ICDWRK(N)
  EXTERNAL FVEC25,MKJAC25

	integer i


	SCALEX=1.0D0
	MAXIT=100
	JACFLG=0
	XTOL=1.0D-13
	FTOL=1.0D-13
	BTOL=1.0D-13
	METHOD=0
	GLOBAL=2
	XSCALM=0
	STEPMX=100
	DLT=-1
	SIGMA=.1
	OUTOPT(1)=0
	OUTOPT(2)=0

	WRITE(*,*)'            ***************************************************'
	WRITE(*,*)'            ***************  BY NLEQSLV METHOD  ***************'
	WRITE(*,*)'            ***************************************************'


	do i=1,5
		CALL X0VCT(X0)
		CALL PRINTX0(X0)					!迭代初值
		CALL NWNLEQ(X0,N,SCALEX,MAXIT,&
								JACFLG,XTOL,FTOL,BTOL,METHOD,GLOBAL,XSCALM,&
								STEPMX,DLT,SIGMA,RWORK,LRWORK,&
								RCDWRK,ICDWRK,QRWORK,QRWSIZ,MKJAC25,FVEC25,OUTOPT,XP,&
								FP,GP,NJCNT,NFCNT,TERMCD)

		write(*,*) 'termcd',termcd
		CALL SAVEX(XP)
		CALL SLV6EQS(XP,FP)   !好奇怪，加上该命令会使精度大大提高！
		CALL PRINTXF(XP,FP)
	enddo
ENDSUBROUTINE SLV25_NLEQSLV

SUBROUTINE FVEC25(X,F,N,FLAG)
  DOUBLE PRECISION X(:), F(:)
  INTEGER  N, FLAG

	CALL SLV6EQS(X,F)

ENDSUBROUTINE
          

SUBROUTINE MKJAC25(RJAC,LDR,X,N)    
	INTEGER LDR
	DOUBLE PRECISION RJAC(LDR,2), X(2)
	INTEGER  N

	RJAC(1,1)=1
	RJAC(1,2)=-1
	RJAC(2,1)=1
	RJAC(2,2)=1
ENDSUBROUTINE
