SUBROUTINE SLV6EQS(X,F)
	USE FSBR
	USE NRTYPE
	IMPLICIT NONE
	REAL(DP), DIMENSION(6), INTENT(IN) :: X
	REAL(DP), DIMENSION(SIZE(X)), INTENT(OUT) :: F
	REAL(DP), DIMENSION(SIZE(X)) :: FUNCV
	CHARACTER(LEN=1)			:: TAB=CHAR(9)
	REAL(DP)	::ALPHA,BETA,ALPHAI,ALPHAO
	REAL(DP)	::OMGI,OMGO
	REAL(DP)	::OMGX,OMGY,OMGZ
	REAL(DP)	::XIXO,XIXI,XIYO,XIYI,PSIO,PSII
	REAL(DP)	::NUM,DEMO !局 部变量，分子、分母
	REAL(DP)	::CAI,CAO,SAI,SAO
	REAL(DP)	::TXI,TYI,MXI,MYI,MZI
	REAL(DP)	::TXO,TYO,MXO,MYO,MZO
	REAL(DP)	::MGZ,MGX,FC,P_I,P_O
	REAL(DP)	::DTI,DTO
	REAL(DP)	::RO,RI
	REAL(DP)	::E
	LOGICAL		::OUTER
	INTEGER		::I
	REAL(DP)	::TEMP

	OMGI=BR%OMGI
	OMGO	=X(1)
	OMGX	=X(2)    
	OMGY	=X(3)
	OMGZ	=X(4)
	ALPHAI=X(5)
	ALPHAO=X(6)

	CAI=COS(ALPHAI)
	SAI=SIN(ALPHAI)
	CAO=COS(ALPHAO)
	SAO=SIN(ALPHAO)

	TYO=BR%BALNO(1)%OUT%TY
	TYI=BR%BALNO(1)%INN%TY
	P_O=(BR%ALOAD/BR%Z+TYO*CAO)/SAO
	P_I=(BR%ALOAD/BR%Z-TYI*CAI)/SAI

	BR%BALNO(:)%INN%P =P_I 
	BR%BALNO(:)%OUT%P =P_O 
	CALL GETPCHAXIS()

	DTO=BR%BALNO(1)%OUT%APP
	DTI=BR%BALNO(1)%INN%APP
	RO=BR%R-DTO/2.0_DP !接触中心变形后与滚动体中心的距离
	RI=BR%R-DTI/2.0_DP !同上

	E=ABS(BR%ICOM%RX2)+ABS(BR%ICOM%RY2)-(BR%BALNO(1)%AI+BR%BALNO(1)%INN%APP)*CAI

	TEMP=OMGY*CAO+OMGZ*SAO
	NUM	= E*OMGO-RO*(TEMP-OMGO*CAO)
	DEMO=(E*OMGO+RO*(TEMP+OMGO*CAO))/2.0_DP		!	DEMO=OMGO*(E+RO*CAO)!	DEMO=RO*TEMP	
	XIXO=NUM/DEMO
	NUM	=RO*OMGX   
	XIYO=NUM/DEMO
!	NUM	=SQRT(BR%BALNO(1)%OUT%AB)*(OMGZ*CAO-OMGY*SAO+OMGO*SAO)	!要命呀
	NUM	=(OMGZ*CAO-OMGY*SAO+OMGO*SAO)
	PSIO=NUM/DEMO

	TEMP=OMGY*CAI+OMGZ*SAI
	NUM = OMGI*E-RI*(TEMP+OMGI*CAI)
	DEMO=(OMGI*E+RI*(TEMP-OMGI*CAI))/2.0_DP		!DEMO=OMGI*(E-RI*CAI)!	DEMO=RI*TEMP	
	XIXI=NUM/DEMO
	NUM =-RI*OMGX  
	XIYI=NUM/DEMO
!	NUM	=SQRT(BR%BALNO(1)%INN%AB)*(OMGY*SAI-OMGZ*CAI+OMGI*SAI)
	NUM	=(OMGY*SAI-OMGZ*CAI+OMGI*SAI)
	PSII=NUM/DEMO

	BR%BALNO(:)%OUT%XIX=XIXO
	BR%BALNO(:)%OUT%XIY=XIYO
	BR%BALNO(:)%OUT%PSI=PSIO
	BR%BALNO(:)%INN%XIX=XIXI
	BR%BALNO(:)%INN%XIY=XIYI
	BR%BALNO(:)%INN%PSI=PSII

	CALL GETCREEP()		!计算FASTSIM所需的各种参数
!	CALL GETCREEP3()		!计算FASTSIM所需的各种参数

	!循环计算接触拖动力
	DO I=1,BR%CYC
		OUTER=.FALSE.
		CALL PREFS(I,OUTER)  
		CALL FASTSIM()
		CALL POSTFS(I,OUTER)
		OUTER=.TRUE.
		CALL PREFS(I,OUTER)
		CALL FASTSIM()
		CALL POSTFS(I,OUTER)
	ENDDO 

	FC =0.0_DP !不考虑离心力
!	FC =br%aload/br%z !不考虑离心力
	MGX=0.0_DP !不考虑陀螺力矩
	MGZ=0.0_DP !不考虑陀螺力矩
!	FC =BR%M1*E*(OMGO**2.0_DP)

!	MGX=BR%IP*OMGz*OMGO
!	MGX=1.0E-3_DP
!	MGZ=BR%IP*OMGx*OMGO
		TXO=BR%BALNO(1)%OUT%TX
		TYO=BR%BALNO(1)%OUT%TY
		MXO=BR%BALNO(1)%OUT%MX
		MYO=BR%BALNO(1)%OUT%MY
		MZO=BR%BALNO(1)%OUT%MZ
		TXI=BR%BALNO(1)%INN%TX
		TYI=BR%BALNO(1)%INN%TY
		MXI=BR%BALNO(1)%INN%MX
		MYI=BR%BALNO(1)%INN%MY
		MZI=BR%BALNO(1)%INN%MZ

		F(1)=(MXO-MXI-MGX)
		F(2)=(-MZO*CAO+MZI*CAI-MYI*SAI-MYO*SAO+MGZ +MZO*SAO-MZI*SAI-MYI*CAI-MYO*CAO)
		F(3)=(TXO-TXI)
		F(4)=(-P_O*CAO+P_I*CAI-TYO*SAO-TYI*SAI+FC)
		F(5)=(TXI*(E-RI*CAI)+MZI*SAI-TXO*(E+RO*CAO)-MZO*SAO) 
		F(6)=((BR%BALNO(1)%AO+DTO)*CAO+(BR%BALNO(1)%AI+DTI)*CAI)/(BR%BALNO(1)%A*COS(BR%BALNO(1)%OUT%ALPHA0))-1.0_DP
	!	FUNCV(7)=BR%CONSTT*(BR%ALOAD/BR%Z-P_O*SAO+TYO*CAO)
	!	FUNCV(8)=BR%CONSTT*(BR%ALOAD/BR%Z-P_I*SAI-TYI*CAI)
	!WRITE(6,"(E23.15,A1,E23.15,A1,E23.15,A1,E23.15,A1,E23.15,A1,E23.15,A1,E23.15,A1,E23.15)")  &
	!	OMGO,TAB,OMGB,TAB,ALPHA,TAB,BETA,TAB,ALPHAI,TAB,ALPHAO,TAB,P_I,TAB,P_O
	!	X(1),TAB,X(2),TAB,X(3),TAB,X(4),TAB,X(5),TAB,X(6),TAB,X(7),TAB,X(8)
	!	TXI,TAB,TYI,TAB,xiyo,TAB,xiyi,TAB,psio,TAB,psii,TAB,FUNCV(6),TAB,FUNCV(8)
ENDSUBROUTINE SLV6EQS