	FUNCTION RTSAFE(FUNCD,X1,X2,XACC)
	USE NRTYPE; USE NRUTIL, ONLY : NRERROR
	IMPLICIT NONE
	REAL(DP), INTENT(IN) :: X1,X2,XACC
	REAL(DP) :: RTSAFE
	INTERFACE
		SUBROUTINE FUNCD(X,FVAL,FDERIV)
		USE NRTYPE
		USE FSBR
		IMPLICIT NONE
		REAL(DP), INTENT(IN) :: X
		REAL(DP), INTENT(OUT) :: FVAL,FDERIV
		END SUBROUTINE FUNCD
	END INTERFACE
	INTEGER(I4B), PARAMETER :: MAXIT=100
	INTEGER(I4B) :: J
	REAL(DP) :: DF,DX,DXOLD,F,FH,FL,TEMP,XH,XL
	CALL FUNCD(X1,FL,DF)
	CALL FUNCD(X2,FH,DF)
	IF ((FL > 0.0 .AND. FH > 0.0) .OR. &
		(FL < 0.0 .AND. FH < 0.0)) &
		CALL NRERROR('ROOT MUST BE BRACKETED IN RTSAFE')
	IF (FL == 0.0) THEN
		RTSAFE=X1
		RETURN
	ELSE IF (FH == 0.0) THEN
		RTSAFE=X2
		RETURN
	ELSE IF (FL < 0.0) THEN
		XL=X1
		XH=X2
	ELSE
		XH=X1
		XL=X2
	END IF
	RTSAFE=0.5_DP*(X1+X2)
	DXOLD=ABS(X2-X1)
	DX=DXOLD
	CALL FUNCD(RTSAFE,F,DF)
	DO J=1,MAXIT
		IF (((RTSAFE-XH)*DF-F)*((RTSAFE-XL)*DF-F) > 0.0 .OR. &
			ABS(2.0_DP*F) > ABS(DXOLD*DF) ) THEN
			DXOLD=DX
			DX=0.5_DP*(XH-XL)
			RTSAFE=XL+DX
			IF (XL == RTSAFE) RETURN
		ELSE
			DXOLD=DX
			DX=F/DF
			TEMP=RTSAFE
			RTSAFE=RTSAFE-DX
			IF (TEMP == RTSAFE) RETURN
		END IF
		IF (ABS(DX) < XACC) RETURN
		CALL FUNCD(RTSAFE,F,DF)
		IF (F < 0.0) THEN
			XL=RTSAFE
		ELSE
			XH=RTSAFE
		END IF
	END DO
	CALL NRERROR('RTSAFE: EXCEEDED MAXIMUM ITERATIONS')
	END FUNCTION RTSAFE
